/**
 * AutoPlay – client-side radio-station behaviour for ACE-Step.
 *
 * When the AutoPlay checkbox is checked:
 *  1. When any visible audio player finishes playing, the "Next Batch" button
 *     is clicked automatically (or polled until it becomes enabled if the next
 *     batch is still being generated by AutoGen).
 *  2. When new audio loads into the first slot after an autoplay-triggered
 *     navigation, playback starts automatically.
 *  3. The checkbox state is persisted in localStorage so it survives page
 *     refreshes.
 */
(() => {
    const AUTOPLAY_ELEM_ID = "acestep-autoplay";
    const NEXT_BATCH_BTN_ELEM_ID = "acestep-next-batch-btn";
    const STORAGE_KEY = "acestep.ui.autoplay";
    const POLL_INTERVAL_MS = 500;
    // 3 minutes: long enough for slow GPU generation but still cleans up if
    // the server never becomes ready (e.g. generation was cancelled or failed).
    const MAX_POLL_MS = 180000;
    const BOOT_POLL_INTERVAL_MS = 200;
    const BOOT_TIMEOUT_MS = 10000;

    let pendingAutoPlay = false;
    let pollTimer = null;
    const seenPlayers = new WeakSet();
    let scanScheduled = false;

    // ── Checkbox state ──────────────────────────────────────────────────────

    const getCheckboxInput = () => {
        const wrapper = document.getElementById(AUTOPLAY_ELEM_ID);
        if (!wrapper) return null;
        return wrapper.querySelector("input[type='checkbox']");
    };

    const isAutoPlayEnabled = () => {
        const cb = getCheckboxInput();
        return cb ? cb.checked : false;
    };

    // ── Preference persistence ───────────────────────────────────────────────

    const loadStoredPreference = () => {
        try {
            const raw = window.localStorage.getItem(STORAGE_KEY);
            if (raw === null) return null;
            return raw === "true";
        } catch (_e) {
            return null;
        }
    };

    const savePreference = (value) => {
        try {
            window.localStorage.setItem(STORAGE_KEY, value ? "true" : "false");
        } catch (_e) {
            // Ignore storage failures (private mode / quota exceeded).
        }
    };

    // Apply the stored preference to the checkbox by dispatching a trusted-like
    // synthetic change so Gradio's Svelte picks up the update.
    const applyStoredPreference = () => {
        const stored = loadStoredPreference();
        if (stored === null) return; // No stored value — leave default.
        const cb = getCheckboxInput();
        if (!cb) return;
        if (cb.checked === stored) return; // Already matches.
        cb.checked = stored;
        cb.dispatchEvent(new Event("change", { bubbles: true }));
        cb.dispatchEvent(new Event("input", { bubbles: true }));
    };

    // Wire the checkbox to save its state on every user change.
    const wireCheckboxPersistence = (cb) => {
        if (!cb || cb._autoplaySaveWired) return;
        cb._autoplaySaveWired = true;
        cb.addEventListener("change", () => savePreference(cb.checked), { passive: true });
    };

    // ── Next Batch button helpers ────────────────────────────────────────────

    const getNextBatchButton = () => {
        const wrapper = document.getElementById(NEXT_BATCH_BTN_ELEM_ID);
        if (!wrapper) return null;
        // Gradio wraps the <button> in a <div> with the elem_id.
        return wrapper.querySelector("button") || (wrapper.tagName === "BUTTON" ? wrapper : null);
    };

    const isNextBatchEnabled = () => {
        const btn = getNextBatchButton();
        if (!btn) return false;
        return !btn.disabled && btn.getAttribute("aria-disabled") !== "true";
    };

    const clickNextBatchButton = () => {
        const btn = getNextBatchButton();
        if (!btn || btn.disabled) return false;
        pendingAutoPlay = true;
        btn.click();
        return true;
    };

    // ── Polling for next-batch readiness ────────────────────────────────────

    const stopPolling = () => {
        if (pollTimer !== null) {
            clearInterval(pollTimer);
            pollTimer = null;
        }
    };

    const startPollingForNextBatch = () => {
        stopPolling();
        pendingAutoPlay = true;
        const startedAt = Date.now();
        pollTimer = setInterval(() => {
            if (!isAutoPlayEnabled()) {
                stopPolling();
                pendingAutoPlay = false;
                return;
            }
            if (Date.now() - startedAt > MAX_POLL_MS) {
                stopPolling();
                pendingAutoPlay = false;
                return;
            }
            if (isNextBatchEnabled()) {
                stopPolling();
                clickNextBatchButton();
                // pendingAutoPlay stays true so the new audio auto-plays.
            }
        }, POLL_INTERVAL_MS);
    };

    // ── Audio event handlers ─────────────────────────────────────────────────

    const onAudioEnded = () => {
        if (!isAutoPlayEnabled()) return;
        stopPolling();
        if (isNextBatchEnabled()) {
            clickNextBatchButton();
        } else {
            startPollingForNextBatch();
        }
    };

    // Auto-play the player when new audio finishes loading, but only when
    // autoplay triggered the navigation (pendingAutoPlay flag is set).
    // The first player to fire loadedmetadata after autoplay navigation wins.
    const tryAutoPlay = (player) => {
        if (!pendingAutoPlay) return;
        if (!isAutoPlayEnabled()) {
            pendingAutoPlay = false;
            return;
        }
        pendingAutoPlay = false;
        try {
            const playPromise = player.play();
            if (playPromise && typeof playPromise.catch === "function") {
                playPromise.catch(() => {
                    // Autoplay blocked by browser policy – silently ignore.
                });
            }
        } catch (_e) {
            // Ignore play errors.
        }
    };

    // ── Player registration ──────────────────────────────────────────────────

    const registerPlayer = (player) => {
        if (!player || seenPlayers.has(player)) return;
        seenPlayers.add(player);
        player.addEventListener("ended", onAudioEnded, { passive: true });
        player.addEventListener("loadedmetadata", () => tryAutoPlay(player), { passive: true });
    };

    // ── DOM scanning ─────────────────────────────────────────────────────────

    const scanAll = () => {
        // Register any audio players that appeared since the last scan.
        // Gradio renders <audio> elements directly in the main document tree,
        // so a flat querySelectorAll is sufficient and avoids the cost of
        // walking every shadow root on each mutation.
        document.querySelectorAll("audio").forEach(registerPlayer);

        // Wire the checkbox persistence listener whenever the checkbox renders.
        const cb = getCheckboxInput();
        if (cb) wireCheckboxPersistence(cb);
    };

    const scheduleScan = () => {
        if (scanScheduled) return;
        scanScheduled = true;
        // requestAnimationFrame coalesces rapid DOM mutations into a single scan
        // per frame, preventing the MutationObserver from running on every
        // individual Gradio state update.
        requestAnimationFrame(() => {
            scanScheduled = false;
            scanAll();
        });
    };

    const startObserver = () => {
        // Limit observation to the Gradio container when available, falling
        // back to documentElement.  The requestAnimationFrame debounce in
        // scheduleScan keeps the per-frame overhead low even on document-wide
        // observations triggered by Gradio's frequent Svelte re-renders.
        const target =
            document.querySelector(".gradio-container") || document.documentElement;
        new MutationObserver(scheduleScan).observe(target, {
            childList: true,
            subtree: true,
        });
    };

    // ── Boot ─────────────────────────────────────────────────────────────────

    // Poll until the checkbox element is present in the DOM, then restore the
    // saved preference and wire persistence.  Gradio components render
    // asynchronously so we cannot rely on DOMContentLoaded alone.
    const bootRestorePreference = () => {
        const started = Date.now();
        const poll = () => {
            const cb = getCheckboxInput();
            if (cb) {
                applyStoredPreference();
                wireCheckboxPersistence(cb);
                return;
            }
            if (Date.now() - started < BOOT_TIMEOUT_MS) {
                setTimeout(poll, BOOT_POLL_INTERVAL_MS);
            }
        };
        poll();
    };

    const start = () => {
        scanAll();
        startObserver();
        bootRestorePreference();
    };

    if (document.readyState === "loading") {
        document.addEventListener("DOMContentLoaded", start, { once: true });
    } else {
        start();
    }
})();
